### ISSUE TITLE
Unable to load the configuration screen

### ISSUE THREAD

**Issue by bbz-233** [Crendgrim/DynamicCrosshair#67]
**What happened**
Unable to load the configuration screen for 'dynamiccrosshair'
Please report to 'dynamiccrosshair' instead of Mod Menu
Java. langNoClassDefFoundError: dev/isxander/yacl3/gui/image/ImageRender

**setup**
MinecraftVerison:1.20.1
Modloader:Fabric 0.14.21 + Fabric API 0.88.1
ModVerison:v7.1+1.20

**Screenshot**
![image](https://github.com/Crendgrim/DynamicCrosshair/assets/92072976/16d586db-4c54-49b8-861a-8517e4ded1f0)

**Comment by Ba-Bao-zhou** [comment]
In short, I cant configure this mod in ModMenu

**Comment by bbz-233** [comment]
YACL(Yet Another Config Lib) Verison:3.0.2
Resolved after updating YMCL to 3.2

**Comment by Crendgrim** [comment]
YACL updated again recently (breaking API again..), I'm currently updating my mods!
